-- DATABASES
CREATE OR REPLACE DATABASE OLIST_DB_BRONZE;
CREATE OR REPLACE DATABASE OLIST_DB_SILVER;
CREATE OR REPLACE DATABASE OLIST_DB_GOLD;

-- SCHEMAS:
-- BRONZE
USE DATABASE OLIST_DB_BRONZE;
CREATE OR REPLACE SCHEMA INGEST;

-- SILVER
USE DATABASE OLIST_DB_SILVER;
CREATE OR REPLACE SCHEMA CLEAN;

-- GOLD
USE DATABASE OLIST_DB_GOLD;
CREATE OR REPLACE SCHEMA ANALYTICS;

-- WAREHOUSE
CREATE WAREHOUSE OLIST_WH 
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 30
  AUTO_RESUME = TRUE;