--PERMISOS SOBRE EL WAREHOUSE Y BASES
GRANT USAGE ON WAREHOUSE OLIST_WH TO ROLE ACCOUNTADMIN;

GRANT ALL PRIVILEGES ON DATABASE OLIST_DB_BRONZE TO ROLE ACCOUNTADMIN;
GRANT ALL PRIVILEGES ON DATABASE OLIST_DB_SILVER TO ROLE ACCOUNTADMIN;
GRANT ALL PRIVILEGES ON DATABASE OLIST_DB_GOLD TO ROLE ACCOUNTADMIN;