--CREO FILE_FORMAT PARA INJESTA
CREATE OR REPLACE FILE FORMAT FF_COMMA
TYPE= CSV
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE
SKIP_HEADER = 1
EMPTY_FIELD_AS_NULL = TRUE
NULL_IF = ('NULL', 'null');

-- CREACION DEL STAGE
CREATE OR REPLACE STAGE OLIST_STAGE_RAW;