-- INTEGRATION WITH SNOWFLAKE
CREATE OR REPLACE STORAGE INTEGRATION olist_s3_integration
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = S3
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = $AWS_ROLE_ARN 
    STORAGE_ALLOWED_LOCATIONS = ('s3://olist-data-raw-2026/');

-- INFO DE STORAGE
DESC INTEGRATION olist_s3_integration;

