USE DATABASE OLIST_DB_BRONZE;
USE SCHEMA INGEST;

-- FILE FORMAT para carga de datos en capa Bronze (CSV estándar Olist)
CREATE OR REPLACE FILE FORMAT FF_COMMA
TYPE= CSV
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE
SKIP_HEADER = 1
EMPTY_FIELD_AS_NULL = TRUE
NULL_IF = ('NULL', 'null');





