--COPY INTO PARA LOS RAW
--CUSTOMERS_RAW
COPY INTO OLIST_DB_BRONZE.INGEST.CUSTOMERS_RAW
FROM @OLIST_DB_BRONZE.INGEST.OLIST_STAGE_RAW/olist_customers_dataset.csv
FILE_FORMAT = OLIST_DB_BRONZE.INGEST.FF_COMMA;

--GEOLOCATION_RAW
COPY INTO OLIST_DB_BRONZE.INGEST.GEOLOCATION_RAW
FROM @OLIST_DB_BRONZE.INGEST.OLIST_STAGE_RAW/olist_geolocation_dataset.csv
FILE_FORMAT = OLIST_DB_BRONZE.INGEST.FF_COMMA;

COPY INTO OLIST_DB_BRONZE.INGEST.ORDER_ITEMS_RAW
FROM @OLIST_DB_BRONZE.INGEST.OLIST_STAGE_RAW/olist_order_items_dataset.csv
FILE_FORMAT = OLIST_DB_BRONZE.INGEST.FF_COMMA;

COPY INTO OLIST_DB_BRONZE.INGEST.ORDER_PAYMENTS_RAW
FROM @OLIST_DB_BRONZE.INGEST.OLIST_STAGE_RAW/olist_order_payments_dataset.csv
FILE_FORMAT = OLIST_DB_BRONZE.INGEST.FF_COMMA;

COPY INTO OLIST_DB_BRONZE.INGEST.ORDER_REVIEWS_RAW
FROM @OLIST_DB_BRONZE.INGEST.OLIST_STAGE_RAW/olist_order_reviews_dataset.csv
FILE_FORMAT = OLIST_DB_BRONZE.INGEST.FF_COMMA;

COPY INTO OLIST_DB_BRONZE.INGEST.ORDERS_RAW
FROM @OLIST_DB_BRONZE.INGEST.OLIST_STAGE_RAW/olist_orders_dataset.csv
FILE_FORMAT = OLIST_DB_BRONZE.INGEST.FF_COMMA;

COPY INTO OLIST_DB_BRONZE.INGEST.PRODUCTS_RAW
FROM @OLIST_DB_BRONZE.INGEST.OLIST_STAGE_RAW/olist_products_dataset.csv
FILE_FORMAT = OLIST_DB_BRONZE.INGEST.FF_COMMA;

COPY INTO OLIST_DB_BRONZE.INGEST.SELLERS_RAW
FROM @OLIST_DB_BRONZE.INGEST.OLIST_STAGE_RAW/olist_sellers_dataset.csv
FILE_FORMAT = OLIST_DB_BRONZE.INGEST.FF_COMMA;

COPY INTO OLIST_DB_BRONZE.INGEST.CATEGORY_NAME_TRANSLATION_RAW
FROM @OLIST_DB_BRONZE.INGEST.OLIST_STAGE_RAW/product_category_name_translation.csv
FILE_FORMAT = OLIST_DB_BRONZE.INGEST.FF_COMMA;