USE DATABASE OLIST_DB_BRONZE;
USE SCHEMA INGEST;

-- CREATE STAGE
CREATE OR REPLACE STAGE olist_raw_stage
  STORAGE_INTEGRATION = olist_s3_integration
  URL = 's3://olist-data-raw-2026/raw/'
  FILE_FORMAT = OLIST_DB_BRONZE.INGEST.FF_COMMA;

    
-- DESCRIPTION INFO STAGE
DESC STAGE olist_raw_stage;
LIST @OLIST_DB_BRONZE.INGEST.OLIST_RAW_STAGE;

