--SELECTION
USE DATABASE OLIST_DB_BRONZE;
USE SCHEMA INGEST;
USE WAREHOUSE OLIST_WH;

-- COPYS INTO FROM S3 TO EXTERNAL STAGE
COPY INTO ORDERS_RAW
FROM @OLIST_RAW_STAGE/orders/olist_orders_dataset.csv
FILE_FORMAT = FF_COMMA;
--VALIDATION_MODE = RETURN_ERRORS;

COPY INTO CUSTOMERS_RAW
FROM @OLIST_RAW_STAGE/customers/olist_customers_dataset.csv
FILE_FORMAT= FF_COMMA;
--VALIDATION_MODE = RETURN_ERRORS;

COPY INTO CATEGORY_NAME_TRANSLATION_RAW
FROM @OLIST_RAW_STAGE/product_category_translation/product_category_name_translation.csv
FILE_FORMAT= FF_COMMA
VALIDATION_MODE = RETURN_ERRORS;

COPY INTO GEOLOCATION_RAW
FROM @OLIST_RAW_STAGE/geolocation/olist_geolocation_dataset.csv
FILE_FORMAT= FF_COMMA;
--VALIDATION_MODE = RETURN_ERRORS;

COPY INTO ORDER_ITEMS_RAW
FROM @OLIST_RAW_STAGE/order_items/olist_order_items_dataset.csv
FILE_FORMAT = FF_COMMA;
--VALIDATION_MODE = RETURN_ERRORS;

COPY INTO ORDER_REVIEWS_RAW
FROM @OLIST_RAW_STAGE/order_reviews/olist_order_reviews_dataset.csv
FILE_FORMAT = FF_COMMA;
--VALIDATION_MODE = RETURN_ERRORS;

COPY INTO PRODUCTS_RAW
FROM @OLIST_RAW_STAGE/products/olist_products_dataset.csv
FILE_FORMAT = FF_COMMA;
--VALIDATION_MODE = RETURN_ERRORS;

COPY INTO SELLERS_RAW
FROM @OLIST_RAW_STAGE/sellers/olist_sellers_dataset.csv
FILE_FORMAT = FF_COMMA;
--VALIDATION_MODE = RETURN_ERRORS;

COPY INTO ORDER_PAYMENTS_RAW
FROM @OLIST_RAW_STAGE/order_payments/olist_order_payments_dataset.csv
FILE_FORMAT = FF_COMMA;
--VALIDATION_MODE = RETURN_ERRORS;