-- LISTADO DE ARCHIVOS SUBIDOS AL STAGE DE SNOWFLAKE
list @OLIST_DB_BRONZE.INGEST.OLIST_STAGE_RAW;

-- PROPIEDADES DEL WAREHOSE
SHOW WAREHOUSES LIKE 'OLIST_WH';

-- VER CONSUMO DE CRÉDITOS
SELECT 
    WAREHOUSE_NAME,
    SUM(CREDITS_USED_COMPUTE) AS TOTAL_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE WAREHOUSE_NAME = 'OLIST_WH'
GROUP BY WAREHOUSE_NAME;